// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ThumbnailService is an autogenerated mock type for the ThumbnailService type
type ThumbnailService struct {
	mock.Mock
}

// Thumbnail provides a mock function with given fields: ctx, videoURL
func (_m *ThumbnailService) Thumbnail(ctx context.Context, videoURL string) ([]byte, error) {
	ret := _m.Called(ctx, videoURL)

	if len(ret) == 0 {
		panic("no return value specified for Thumbnail")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, videoURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, videoURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, videoURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewThumbnailService creates a new instance of ThumbnailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewThumbnailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ThumbnailService {
	mock := &ThumbnailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
