// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// SaveThumbnail provides a mock function with given fields: ctx, videoURL, _a2
func (_m *Storage) SaveThumbnail(ctx context.Context, videoURL string, _a2 []byte) error {
	ret := _m.Called(ctx, videoURL, _a2)

	if len(ret) == 0 {
		panic("no return value specified for SaveThumbnail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, videoURL, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Thumbnail provides a mock function with given fields: ctx, videoURL
func (_m *Storage) Thumbnail(ctx context.Context, videoURL string) ([]byte, error) {
	ret := _m.Called(ctx, videoURL)

	if len(ret) == 0 {
		panic("no return value specified for Thumbnail")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, videoURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, videoURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, videoURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
