name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go mod tidy

      - name: Build server
        run: |
          cd server
          go build -v ./cmd/grpc-thumbnail

      - name: Test server
        run: |
          cd server
          go test -v ./...

      - name: Build client
        run: |
          cd client
          go build -v ./cmd/grpc-thumbnail

      - name: Test client
        run: |
          cd client
          go test -v ./...

