name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go mod tidy

      - name: Run unit tests
        run: |
          cd server
          go test -v ./internal/...

      - name: Start server
        run : |
          mkdir -p storage
          make migrate
          go build -o server ./server/cmd/grpc-thumbnail
          ./server/grpc-thumbnail --config=./server/config/local.yaml &

      - name: Run black box tests
        run: go test -v ./server/tests

      - name: Stop server
        run: killall server
        if: success() || failure()


